# Generated by Django 4.2.30 on 2026-05-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_product_specifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Emoji or icon class', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'year'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_headline', models.CharField(default='Pure Water, Pure Life', max_length=255)),
                ('hero_subheadline', models.TextField(default="Assam's most trusted water purification company. From homes to industries, we deliver clean, safe water solutions with expert service.")),
                ('about_mission', models.TextField(default='Providing safe, clean drinking water to every household and industry in North East India through affordable, reliable water purification technology.')),
                ('about_vision', models.TextField(default='To become the most trusted water solutions brand in North East India, ensuring no family has to compromise on water quality due to cost or availability.')),
                ('about_story', models.TextField(default='Barhamthuri Aqua Solutions was founded in 2014 in Guwahati, Assam, with a simple yet powerful mission...')),
                ('contact_address', models.TextField(default='Ward-4, Bihpuria, Lakhimpur, Assam 784161, India')),
                ('contact_phone', models.CharField(default='+91 8753953744', max_length=50)),
                ('contact_email', models.EmailField(default='barhamthuriaquasolutions@gmail.com', max_length=254)),
                ('whatsapp_number', models.CharField(default='918753953744', help_text='Number only, with country code (e.g. 918753953744)', max_length=50)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('instagram_link', models.URLField(blank=True, null=True)),
                ('youtube_link', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
