# Generated by Django 4.2.30 on 2026-06-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_corevalue_milestone_sitesetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(blank=True, help_text="Can be exact price or range (e.g., '35000-300000')", max_length=100, null=True),
        ),
    ]
