# Generated by Django 4.2.30 on 2026-07-30 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_project_projectimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_bestseller',
            field=models.BooleanField(default=False, help_text='Show this product in the Best Sellers section on the Home page'),
        ),
    ]
